### ISSUE TITLE
not responsive opponentcards and mycards class.

### ISSUE THREAD

**Issue by Etan31** [Etan31/UNO-offline-game#1]
The spaces of the top and the bottom of the card deck.

**Comment by Anku5hn** [comment]
This is an issue even for the hidden opponent cards for now. In tablets and other smaller sized devices, some of the opponent cards are visible. To solve it, we can use the same class and either shorten the height of the outer container for small devices, or we can increase the height of the back-cover card.

**Comment by Etan31** [comment]
Responsive card images and it's containers. You may shorten the height of the outer container. Are you working on this now? Let me know so I can I assign this request to you.

**Comment by Anku5hn** [comment]
I'm not currently working on it right now, but I can. Assign it to me, I'll let you know once it's done.

**Comment by Anku5hn** [comment]
I have created a PR with adding the necessary styles for the breakpoints.
