### ISSUE TITLE
Automatically add new score when the button is clicked inside the modal `gameWinner-modal`.

### ISSUE THREAD

**Issue by Etan31** [Etan31/UNO-offline-game#24]
This JavaScript will be related to #23 modal creation.

The button with a function `AddScore()` will add score to which player is on the parameter. 
You can call the function add an score to which player you call, like this `addScore('player1')` for adding score to player1 or `addScore('player2')` for the adding onto player2's score. 

The modal #23 will close and then add the score.

**Comment by Zek1t0** [comment]
Hello, I’m interested in working on this issue. Could you confirm if it’s still available for someone to take? If you have any specific guidelines or suggestions for tackling this, please let me know. Thank you!

**Comment by Etan31** [comment]
Hi @Zek1t0,  

This issue (#24) is still open and has no assignees yet. I’ll be happy to assign it to you if you’re interested.  

The `addScore(player)` function is already implemented, so all you need to do is call it when the button is clicked, like this:  
- `addScore('player1')` — to update Player 1’s score.  
- `addScore('player2')` — to update Player 2’s score.  

However, the button `<button id="continue">Continue</button>` is part of the modal described in **issue #23**.  

---

### If You Want to Work on Both Issues (#23 and #24):  
1. First, create the modal as outlined in issue #23.  
2. Then, integrate the button functionality described in issue #24 using the existing `addScore(player)` function.  

Let me know how you’d like to proceed. Looking forward to your contribution! 😊

**Comment by Zek1t0** [comment]
I was about to test my code and I saw that the game has a problem, when you run out of cards of the same color and you grab new cards, the game stops working. Does this problem happen to you on your computer too?

**Comment by Etan31** [comment]
I'm not entirely sure—it could be a bug. Could you provide more details? Alternatively, feel free to create an issue for it if needed.
