### ISSUE TITLE
Player2 cards are not hidden.

### ISSUE THREAD

**Issue by Etan31** [Etan31/UNO-offline-game#5]
Their cards should not display it's card's information. The cards of player2 should be displayed in `back-cover.png`.

**Comment by Anku5hn** [comment]
Hi there!

I have created pull requests solving this issue for desktop players. As mentioned in the previous comment, I have used back-cover.png in assets to hide the player2 cards.

**Comment by Etan31** [comment]
Yes, feel free to work on that. To streamline the review process, please combine related changes (e.g., HTML, scripts, and styles) into a single PR. Thank you!

**Comment by Anku5hn** [comment]
I have created 3 different PRs for HTML, scripts, and styles. 2 of my PRs are still remaining and are essential for the code to work. I will keep that in mind and create a single PR combining the changes next time.
